[Lc] # Layer Counter

  [Lc.bitmatcher]
    sketch = ["HP"]
    data = "../data/kosarak.bin"
    cnt_method = "InPacket"
    format = [["flowkey", "padding", "timestamp", "length", "padding"], [13, 3, 8, 2, 6]]
    bkt_rate = 3.0


[HP]

  [HP.para]
    depth = 3
    width = 8002

  [HP.data]
    hx_method = "TopK"
    threshold_heavy_hitter = 5000

  [HP.test]
    update = ["RATE"]
    heavyhitter = ["TIME", "ARE", "PRC", "RCL", "F1", "RCD"]
