[Lc] # Layer Counter

  [Lc.bitmatcher]
    sketch = ["CM"]
    data = "../data/zipf-200.bin"
    cnt_method = "InPacket"
    format = [["flowkey", "padding", "timestamp", "length", "padding"], [13, 3, 8, 2, 6]]
    bkt_rate = 4.0


[CM]

  [CM.para]
    depth = 4
    width = 4000001

  [CM.test]
    update = ["RATE"]
    query = ["RATE", "ARE", "AAE", "RCD"]

