[Lc] # Layer Counter

  [Lc.pyramid]
    sketch = ["CS"]
    data = "../data/kosarak.bin"
    cnt_method = "InPacket"
    format = [["flowkey", "padding", "timestamp", "length", "padding"], [13, 3, 8, 2, 6]]
    width_cnt = [6, 6, 6, 4]


[CS]

  [CS.para]
    depth = 4
    width = 64001

  [CS.test]
    update = ["RATE"]
    query = ["RATE", "ARE", "AAE", "RCD"]
