[Lc] # Layer Counter

  [Lc.stingy]
    sketch = ["CM"]
    data = "../data/zipf-075.bin"
    cnt_method = "InPacket"
    format = [["flowkey", "padding", "timestamp", "length", "padding"], [13, 3, 8, 2, 6]]


[CM]

  [CM.para]
    depth = 4
    width = 2001

  [CM.test]
    update = ["RATE"]
    query = ["RATE", "ARE", "AAE", "RCD"]
