[CM]

  [CM.para]
    depth = 4
    width = 25001

  [CM.data]
    cnt_method = "InPacket"
    data = "../data/zipf-150.bin"
    format = [["flowkey", "padding", "timestamp", "length", "padding"], [13, 3, 8, 2, 6]]

  [CM.test]
    update = ["RATE"]
    query = ["RATE", "ARE", "AAE"]

